extends Node

class_name GlobalState

var settings_config_location: String = "user://user_settings_v3.json"
var top_panel_card_resource:Resource = load("res://assets/scenes/top_panel.tscn")
var arena_names:Array[String] = ["Very Serious Bowl Arena", "Underpass Arena", "Orange Squeezer Arena", "Halo Arena", "Hedge Slopes Arena", "Mountain Arena", "Wave Arena", "Ridges Arena", "Da Eye Arena", "Bouldering Arena"]
var arena_resources:Array[Resource] = [load("res://assets/scenes/arena0.tscn"), load("res://assets/scenes/arena1.tscn"), load("res://assets/scenes/arena2.tscn"), load("res://assets/scenes/arena3.tscn"), load("res://assets/scenes/arena4.tscn"), load("res://assets/scenes/arena5.tscn"), load("res://assets/scenes/arena6.tscn"), load("res://assets/scenes/arena7.tscn"), load("res://assets/scenes/arena8.tscn"), load("res://assets/scenes/arena9.tscn")]

var ult_names:Array[String] = ["Dash", "Jump", "Shockwave", "Unstoppable", "None"]
var ult_colours:Array[Color] = [Color.RED, Color.GREEN, Color.BLUE, Color.BLACK, Color.WHITE]
var default_game_state: Dictionary = {
	"settings": {
		"volume": {
			"master": 100.0,
			"music": 50.0,
			"sfx": 100.0,
			"voices": 50.0,
			"ambient": 100.0
		},
		"gameplay": {
			"dynamic_camera": true,
			"fullscreen": false,
			"easymode": false
		},
		"tutorial_complete": false
	},
	"next_match": {
		"num_cpus": 3,
		"arena_id": 0,
		"rewards": {
			"increase": {
				"name": "impulse_speed",
				"value": 2.0
			},
			"decrease": {
				"name": "red",
				"value": -0.5
			},
			"rewards_text": "+2.0 Impulse Speed\n-0.5 Red"
		}
	},
	"stats": {
		"Dexterity": 2, # +move speed, +spin speed, -weight, +green
		"Power": 2, # +force, +weight, (+right speed), +red
		"Special": 2, # +rocket dash, +force, +ult, +blue
		"Ult": 0, # id for ultimate ability
		"wins": 0
	}
}
var game_state: Dictionary = default_game_state.duplicate(true)

func read_json(path: String) -> Dictionary:
	if not FileAccess.file_exists(path):
		return {}
	var json_string = FileAccess.get_file_as_string(path)
	var json_dict = JSON.parse_string(json_string)
	
	return json_dict

func load_settings():
	# check if user has settings at settings_config_location
	if not FileAccess.file_exists(settings_config_location):
		save_settings()
	game_state = read_json(settings_config_location)
	game_state["stats"]["Dexterity"] = clampi(game_state["stats"]["Dexterity"], 1, 5)
	game_state["stats"]["Power"] = clampi(game_state["stats"]["Power"], 1, 5)
	game_state["stats"]["Special"] = clampi(game_state["stats"]["Special"], 1, 5)
	
	toggle_fullscreen()
	
func toggle_fullscreen():
	if game_state["settings"]["gameplay"]["fullscreen"]:
		DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_FULLSCREEN)
	else:
		DisplayServer.window_set_mode(DisplayServer.WINDOW_MODE_WINDOWED)
	

func save_settings():
	# save the results
	var json_string := JSON.stringify(game_state)
	# We will need to open/create a new file for this data string
	var file_access := FileAccess.open(settings_config_location, FileAccess.WRITE)
	if not file_access:
		print("An error happened while saving data: ", FileAccess.get_open_error())
		return
		
	file_access.store_line(json_string)
	file_access.close()
	



# Subscribers to ShrikeGames YT that don't have their subs hidden
var top_names:Array[String] = [
	"juniper",
	"frenchferretsp1p335",
"miru",
"NoiR",
"Haizumi",
"sukida",
"Netsurou",
"Mike_",
"Helmir",
"Hamakaze",
"PixlTheAxolotl",
"[WD] WatameVirus",
"Syro",
"Sonic_md | 스타크래프트: 브루드 워 리마스터드",
"ArianaGrandeLife",
"D G",
"grolich",
"melanchlorin",
"Lux Aeterna Audio",
"XxLemonxX",
"Maunomau Clips",
"Joshua Blanck",
"♡1x1x1x1☆",
"Sami branco",
"DownrightSuperb",
"Terry Jay Productions",
"Kenton Barks",
"Kate Ground",
"theRCB",
"Neeyo",
"StaviKay",
"Eshwar",
"Blake",
"A Good Man",
"Daniel Parente",
"JR ED",
"spidergem1",
"AJ Ellis",
"derf6060",
"Soya",
"Matthew Lloyd",
"IEV Rahari",
"MagicTools",
"Fran",
"WhyKhi",
"Ravin Othman",
"Nils Bölting",
"Kat",
"COZYTW",
"Neo Slasher",
"neonepik",
"Flvtbush",
"(WD) PunkPimster (パンク・ピムスター)",
"BonadanAlloy",
"HD Daedthedk",
"Joah George",
"Shawn Sig",
"Ghost Schmidt",
"TrentStudios28",
"Omid Bayat",
 "German Borba",
"Malkis the Plague Raven",
"alt123 padron",
"Gagup",
"كل شيء",
"Mohamed Talaat Harb",
"angelslayer gaming",
"Meg Mog",
"Wagon Train Media",
"Edwin Rodriguez",
"Jorge Peida Leite",
"Dionysian Apollos (Olympic Ampitheatre)",
"Gerry Weber",
"SmashUp MashUp",
"TiBBs House",
"harrisonyek",
"zrossk",
"Verhunqert Mc",
"Sanic Swaghog",
"Soulend",
"Dean Campbell",
"Alex Z",
"JAMES FFS",
"Hells_13thDragon",
"Morigen",
"Harald",
"ThyEnd _",
"_gerrit",
"Pabloo",
"Vr keep it live",
"Healbruise",
"will G",
"Kennedy",
"Manolol",
"YukiYeah",
"Просто Мы",
"Redrwbyvr21",
"Kevins Univers",
"Moshe Cristel",
"Houston Witty",
"Hadi Hmidani",
"HexNectar",
"Eugenia Marsicovetere",
"Ethereal Despair",
"Kóta",
"szatuchny",
"emaecks",
"Sven Erik Lysell",
"renato Oriano",
"Edgar Poe",
 "Yuri Guimarães (POBLAYURI)",
"Ninjapro123",
"David Williams",
"AlienTree Gaming",
"Naruto Sims",
"Bryan Anthony Koptian Senske",
"phoenixflip",
"Stephan Strauss",
"TheShadow4884",
"aaron jamal",
"Ardiawan Bagus Harisa",
"Dan c",
"Striver",
"CHRIS E ",
"nunya",
"Lichatai",
"Inertiaddict Inertiatic",
"RioJay's TV",
"Aver",
"Christopher",
"WellDewEye",
"Huayi Gao",
"raginhomosapien",
"datguy635",
"db.2x",
"TONYdaGAMER",
"Hardcorakias",
"perfect fitz",
"MadOverseer",
"Hoodie-ni",
"SADxStrike4Skillz",
"Fabi",
"Pootin the Lizard Wizard",
"infernx193",
"rmcnaugh",
"TheFallenHero 2370",
"Kagesh53150",
"Gijs Tempel",
"otejoy",
"Reuben Cheung",
"Wallace Realm",
"WhiteCrafter",
"Andersom de oliveira marcos",
"Tim Kim",
"Jung Cooked Nutz",
"hobert bryant",
"FierinMahLazor",
"Jenn Kauffman",
"jacob bullon",
"Carlos Eduardo",
 "Sonny218",
"Tobias Gepp (Objectname)",
"jd15halo",
"bomber92ful",
"Bounty Hunter",
"Michael Ferguson",
"Waill Tatari",
"RondouillarD",
"Isabella Travassos",
"Lucas Mendes",
"Wolfsson",
"Alban Bodo",
"alpernatif35",
"Rasec Vargas",
"AJ Jackson",
"djoecks26",
"WONSINCITY1",
"Timothy Hobbs",
"CJ King",
"Maciej Kurtyka",
"Rara Nindita",
"tunedmd64",
"RedRumStudio",
"Trevent Wilborn",
"Peter Noone",
"Cory Todd",
"leehsiNTheThird",
"The Kingsley Family",
"KindNight",
"Ali Glen",
"Joshua Morse",
"Am0109-k1y",
"zn tith e",
"Ladislav Sunek",
"Alex Brady",
"Andreas Rolsted",
"Joseph360",
"DietsBeats",
"Live Bait",
"Garudahell",
"Nazgarth",
"Robert Stone",
"slamhamjr",
"John Kenney",
"CILinkzSpre3",
"Jeff Blackstone",
"Aiden AV",
"Bilbo Cattings",
"mon mon",
"Petrus_the_Rock",
 "HouOuin KyomA",
"Grandpa Elmo",
"MultiBoFaHaD",
"Jeyce",
"Shubham Sharma",
"MGV - Matteo Ghittoni Videos",
"teamkawaiikru",
"Karesse Holden",
"arlem525",
"Darok Deed",
"RoboToasterChad",
"Tom Lonergan",
"TotallynotStone",
"Bi",
"Wolf",
"juju gonçalves",
"Trix022v",
"Fedor Yakovlev",
"Bartt PG",
"klemen kogovšek",
"anoxisstudios",
"Mohamed Ghassen Brahim",
"Rockmodd",
"Lazulauf Ca",
"Navdhit Bedi",
"Chris Brisson",
"Eon",
"Liam Einarson",
"Anja Kunkel",
"Meri Mitrevska",
"Flexan Taylor (YickleSickle)",
"2 1 (Erroru45)",
"Matrix 6000",
"Recordflybass",
"Sam",
"Kingmonsterman",
"Dark Witch Nynx",
"MrJellybane",
"cecilkorik",
"Mertcan Kara",
"CLUPShow",
"Narcycis Khan",
"Yi kimsron",
"historicgamer",
"Franky Malts",
"Agar",
"Jacob Holt",
"Tommaso Lodolo",
"Joshua Moke",
"CrustyBung",
 "bigjaydogg1",
"JonasTheQuestionable",
"JM Olarte",
"_Absalom _",
"Yogi2Much 096",
"Mahim Romero",
"Shorts4hel",
"Rat Cavern Woodworks",
"Amber Rowe",
"Xtremely Venomus",
"Nicolas Dreyer",
"The Lord of Cryptids",
"MrNelson007",
"Leagas",
"Simon Bl.",
"Gribi Gaming",
"Cj Clippa",
"Map Atay",
"Damien",
"Blazky",
"Viljami Kalliainen",
"Red Keys",
"RobotLV",
"Marina rocha",
"Jason Wu",
"root",
"zevess",
"Devin Roos",
"jake wilde",
"Jessica Hyche",
"TheRadDoc",
"Melissa Wright",
"Gayo Ilac",
"Oliver Williams",
"Mr. Treefeather",
"Jjef",
"Froginalog",
"CJ Howl",
"Matti Torppa",
"Excussa",
"kami kon",
"Clark Diercks-Lenn",
"Norbert Polak",
"Deshawn Lewis",
"The mostad",
"Aws Believer",
"green mushroom",
"Twolegz",
"Silver Selene",
"vived",
"Eliarith",
"Fernando C",
"amadeus amadeus",
"Stallion DC",
"Jaydewulf",
"shane hileman",
"Datamid",
"Marc Friedberg",
"Fam Richards",
"Viktor Fulop",
"ANGRY UNICORNS",
"Hap Perry",
"Desktop Goose",
"Thomas Minear",
"Luke Palermo",
"Angel Payne",
"Scent",
"Crashing Hard",
"german burillo",
"Pedro Dias (M1hawk)",
"Jerald Pearson",
"juan diego lugo",
"w23tx4",
"Сеющий",
"No So",
"spadez011",
"FreshJB2",
"camcam",
"Victor Chabot",
"jtgjsw817",
"MANEEEE48",
"Nathan Hinds",
"John Garlasco",
"Boris Graafland",
"lefront",
"noakey",
"AnimatedMelodys",
"Andrew Chen",
"Purple Motion",
"FuHang89",
"Tomasz Choroś",
"Tomas",
"Edwina Thomas",
"meshal alenezi",
"Travles Williams",
"Denise Zahradnik",
"Ricardo Oliveira",
"Corey C",
"Сергей Якубенко",
"Mr Hyde",
"the_first_Human",
"Bailey Schneider",
"Harry potter",
"Steven Mclean",
"Mayanoe story",
"Иван Андреевич Марков",
"Felipe Albuquerque",
"26Norik",
"Chris Kaluila",
"Tanmoy Khan",
"Avarita",
"Andreas Winkler",
"Keeroh",
"Vasi Chirita",
"Benjamin Wolf",
"NINE_A",
"amr samy",
"Evan Bacon",
"fikri jufri",
"jean-philippe staelen",
"Jan Marlo",
"William H",
"Alif",
"ScipionNyshade",
"Luca Tagliavini",
"Korie McNamara",
"A Gonzalez",
"Jessica Jones",
"Thomas Harby",
"Marc Medenilla",
"Nolan Floyd",
"Justin",
"hassu61",
"VincE V",
"gta 5",
"zefa Cardoso",
"EarlOdinod",
"Martin Surman",
"Sten Li",
"Plastic_flamingo",
"AarbozT",
"jens bendik grande",
"Connor Gibb",
"asd",
"Luke Stander",
"Trung Ha",
"megaralph12345",
"Abdulla Mesmar",
"1RallyMK",
"gill manus",
"Felipe Bastos",
"Dyl M",
"Jose Alvarez",
"ZShalafi",
"Amar Teotia",
"Director Joseph Wu",
"Oumaima Touhemi",
"sfghdfghjfh",
"Sandra Fernandes",
"Delucidine Sol'rey",
"Caleb Mitchell",
"Aesino",
"RameGaming",
"Dan Walker",
"Siraj",
"Fayee520",
"Miłosz",
"Michael Brendel",
"Aligor 98",
"oliver marinus",
"Zolile Mhlauli",
"Travis Farewell",
"Space Aids",
"Aaron Hayford",
"Amanda C",
"darchypeacecraft",
"Florian Meding",
"andrewsallison",
"David Schaffner",
"Matthew Cassiani",
"Kroeger29",
"Raul Pazetto",
"frank paterson",
"Emmanuel Johnson",
"Adam Herman",
"Anton Bobilev",
"Mason Geier",
"Darthvader 165",
"ItworksAlex",
"oo00sadmachines00oo",
"Sylvia Choong",
"Francesco Colletti",
"SSG Viper",
"Kzyh43",
"jake davies",
"Markus Beckert",
"Richard Charming",
"Naufal Hanif",
"Stephen MLG Hawking",
"TheBloodynevermore",
"Drbananabow",
"hugo encinas",
"Matt Freund",
"Darketh Bane",
"Leif Walterman",
"Pawel Zubrycki (Zuber)",
"voyagebass",
"Meepersmerped",
"CB123966",
"Amaia Yael",
"destiny streamer",
"Tanner Alexander",
"John Wiklund",
"Adrian Heredia",
"Scumbag HaggisSlayer",
"what〈|〉a〈|〉player",
"Brian Hedge (Highlander61)",
"Chad Reifsnyder",
"Yoona Minho",
"L Jean",
"Danut Mereoiu",
"Yana Shutihina",
"Rain Copyright",
"Giacomo",
"Ivan Bruselas",
"Daniel Bernardes",
"Stoian Doru",
"SumUniqueName",
"sasha prilipko",
"Gabriel Ferraz",
"Lethio Dire",
"Shane Blackmore",
"Tamás Torda",
"Breno QGC",
"Brian Morck",
"brian carver",
"underage duck",
"Onside Silver",
"Rene Lopez",
"Младен Петровић",
"strike OLD",
"Han Zhang",
"AbyssalGuardian",
"Daniel Wright",
"Yousef Samhan",
"Sheep (Sheep)",
"oykaer",
"InkSkratchers",
"monitorman06",
"Paul ",
"Jurre de Greef",
"Vlad Calu",
"Todd Alloway",
"Sarwar Nst",
"Daniel Neufeldt",
"galih rahmadhani",
"Blake Douglas",
"Jacob Pugh",
"J",
"Ni Magus",
"q8y 9a7i",
"m1tch",
"Gibby gaming",
"sjoerdpeeters111",
"Jonathan Parnell",
"Adolf",
"Simon Kucharski",
"manolo vid (2manololo)",
"Ilya Zhavoronko",
"Wyatt Dorweiler",
"NickelousCage",
"Alex Snider",
"a132431",
"kanone Bruch",
"Sung Baek",
"Johan Hellstedt",
"Matthew Avery",
"Harley Sifflet",
"Cookster",
"Kay",
"SinanjuRise",
"Dylan Maness",
"ParbearGaming",
"MsBonClay",
"LawNown",
"Caine Longstaff (Cainey)",
"ChiCkeNlegProjeCT",
"Jacob Mann",
"Andrew Mathews",
"ANoddTHING",
"dagger Boi",
"Jacob Stoskopf",
"pillam",
"goddangit200",
"zahin zahwan",
"albe8809",
"Amelia Sigmundson",
"Ednilson Dava",
"Blade Sargent",
"Belly",
"darklac",
"RGistaken",
"Jeptoo Kipkech",
"Tahseen Faishal",
"daniel tusa",
"Shmeh",
"TheBeardyDan",
"David Woods",
"Robert Morris",
"tackbracka",
"deadmercz101",
"Brayan",
"Roy Tsang",
"James Sawyer",
"Farkas Mátyás",
"Sejr Almbjerg",
"Xiaotian Zhang",
"Matt Zarro",
"Elvis Chinchilla",
"matt politte",
"Raizen The Paradoxical Bastich",
"Rhyfel",
"Jordi Sole Rovira",
"Antonio Filipe Vieira",
"blodd07",
"Bradshaw",
"Gerry Carson",
"Undoinghydra03 Ho",
"The dab king ",
"Alessandro Furrer",
"Lars Kruik",
"Frederik Reitmeier",
"RikSco",
"New Zikos",
"Seth",
"robert devonta",
"Michael Poulsen",
"Bartosz Bielecki",
"Ian Hales",
"刘罡",
"Kl Kl",
"Jvvictor",
"Sir Bananas",
"drac0-v6d",
"wearablesnake",
"Frostycog",
"Genshuku",
"LL",
"emoduck:>",
"shifty",
"catsy"
]
func get_random_name():
	return top_names.pick_random()
